TEMP_DIRECTORY: '/root/tmp' 
LOG_DIRECTORY:  '/root/logs'
#AWS
## default 
AWS_ACCESS_KEY_ID: null
AWS_SECRET_ACCESS_KEY: null
AWS_DEFAULT_REGION: null

## S3
S3_BUCKET_NAME: 'atx-cloud-dev'


## RabbitMQ 
RABBITMQ_HOST: rmq:5672
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: root
RABBITMQ_PASSWORD: defpass

## REDIS

REDIS_HOST: redis:6379
REDIS_PORT: 6379
REDIS_PASSWORD: defpass

#Flask
MAX_CONTENT_SIZE: 10000000000

